### ISSUE TITLE
the tool does not work

### ISSUE THREAD

**Issue by avaraj708** [OfficeDev/DLPmigrationassistant#26]
We try to migrate DLP rules from (forcepoint to Purview) but the tool does not work. Appear the following error:

ERROR: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.56.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'.

![image](https://github.com/OfficeDev/DLPmigrationassistant/assets/173824093/251d333d-21e4-4110-a5c2-017d535c0c02)

here the log:
[Migration_assistant2024_06_25-093832.log](https://github.com/user-attachments/files/15974066/Migration_assistant2024_06_25-093832.log)
 
thanks for your support.

**Comment by akedia24** [comment]
Issue is resolved on latest version v2.1.2.0.
